### ISSUE TITLE
what IS

### ISSUE THREAD

**Issue by thomasTAT** [SingularityLabs-ai/beyond-bard-mini#2]
**Describe the bug**

**Desktop (please complete the following information):**

- OS: windows11
- Browser edge
- Version: latest
- 
![image](https://github.com/SingularityLabs-ai/beyond-bard/assets/109513632/820f7d1d-9980-40b0-924c-41beb6ae5166)

**Comment by ishandutta2007** [comment]
@thomasTAT We are aware of such scenarios. I will tell you how it works and why it happens. We try to get thc the suggested questions within a single prompt to save time and sometimes bard don't suggest any followup questions. If it occurs too frequently we may have to change the way we retrieve the followup questions. Is it intermittent of too frequent for you ?
