### ISSUE TITLE
Inclusion of Wikipedia Page Summaries

### ISSUE THREAD

**Issue by divyaprakashdp** [SingularityLabs-ai/beyond-bard-mini#9]
**Is your feature request related to a problem? Please describe.**
Summary of Wikipedia pages is not available in the current app, limiting the comprehensiveness of the content provided.

**Describe the solution you'd like**
I would like the app to include a feature that generates summaries for Wikipedia pages, similar to the summaries it provides for other webpages. This will enhance the user experience by offering concise information for Wikipedia content.

**Describe alternatives you've considered**
NA

**Additional context**
![image](https://github.com/SingularityLabs-ai/beyond-bard-mini/assets/20191885/c81b661e-b0d1-46f3-82d8-d9c79e59b23a)

**Comment by ishandutta2007** [comment]
This was fixed as addressed [here](https://discord.com/channels/1109388259324330066/1156985597454450719/1190620925104771192)
